[install]
is_configured = false
build = %%BUILD%%

[ui]
is_visible = 1
label = %%APPID%%

[launcher]
author = hire.vladimir@gmail.com
description = https://github.com/hire-vladimir/SA-cim_vladiator
version = %%VERSION%%

[package]
id = %%APPID%%

[id]
name = %%APPID%%
version = %%VERSION%%
